### PR TITLE
add `typings` field to package.json

### PR DESCRIPTION
**Pull request by postspectacular**
required for TypeScript to find the type declarations

### CODE REVIEW

**Comment by ygoe** [comment]
Sure it's not `types` instead of `typings`? I don't know it, just looked this up: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by postspectacular** [comment]
Good point, but it seems they're synonymous (I've been using `typings` for my own libs), from the same document:

> Note that the "typings" field is synonymous with "types", and could be used as well.

I guess, `typings` is the older version, happy to change it...

**Comment by postspectacular** [comment]
Oki, and reading even further it seems this whole PR is obsolete, since you're using `files` in your package:

> Also note that if your package.json includes the "files" property the "types" property will be ignored. In that case you need to pass your main declaration file to the "files" property as well.

Mea culpa!

Next question then is - do you have an ETA for 1.0.3? :)

**Comment by ygoe** [comment]
Thanks for clearing this up. No, there's no ETA for the next release yet. I'd first try to resolve a few issues in my limited time. I guess if this isn't happening a new release would be due at last in a month or so.

**Pull request closed without merging**
