### PR TITLE
Skip encoding properties with `undefined` value

### LINKED ISSUE #20: Skip serializing properties with `undefined` values
Similar to `JSON.stringify` behavior, properties whose value is `undefined` should *not* be serialized as `null` in msgpack. Undefined means: _undefined_, which is decidedly different from a defined value of `null`.

Observe the following node interactive:
```
> msgpack.deserialize(msgpack.serialize({a:'a',b:undefined}))
{ a: 'a', b: null }
> JSON.stringify({a:'a',b:undefined})
'{"a":"a"}'
```

It's convenient to use `undefined` as a value to suppress its encoding, but this library ignores that technique.

If you can't change the default behavior, what if we added an option under which `undefined` properties would be skipped? 

I am willing to send a PR.

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #20

* [ ] How do I update the .min.js files?

### CODE REVIEW

**Comment by ygoe** [comment]
What should we do about `undefined` values in an array? That was mentioned as an anomaly in the other issue you referenced.

I don't have a strong opinion about making this change optional. I'll have to test it with my applications but don't expect any breaks here as I'm not commonly using `undefined` values. In case any sort of configuration should be necessary, that would probably go as a second parameter that gets an object of such options.

The minified file is created with [Mini Web Compiler](https://github.com/ygoe/MiniWebCompiler), the project file miniwebcompiler.json is in this repository.

**Comment by AArnott** [comment]
> What should we do about undefined values in an array?

These should convert to `null`. `JSON.stringify` does the same: it omits `undefined` from objects but converts them to `null` in arrays. While omitting properties from objects doesn't change the rest of the object, omitting them from arrays would shift the position of all later array elements. 

I will try to update the minified files too.

**Comment by AArnott** [comment]
Hmmm... I guess if I need to install this mini-web compiler, I'd rather not do so. Would you mind updating this PR with the changes to the minified files?

FWIW, I feel these web-ready files are perhaps unnecessary. It seems that a great many NPM packages work on the web, but leave the web-ification of the javascript to the final application, which may run webpack, or browserify, or other tools including perhaps your own mini web compiler. I find it odd that an individual NPM package would itself contain as source code, multiple copies like this.

**Comment by ygoe** [comment]
Good point about including the min files in the release. I've just checked in the other two packages we use in our application and both also contain the min files. So I'd just keep it like this. Every user is free to use their own packing tools but they won't have to with the file already included.

I'll merge this PR and update the min file separately, I don't know how to do it else (or it would be much more work).

**Pull request merged**
