### PR TITLE
Fixed float deserialization when TypedArray.byteOffset is nonzero

### LINKED ISSUE #14: Wrong float deserialization from typed arrays with non-zero byteOffset
When deserializing from an Uint8Array which has a non-zero byteOffset, float values go wrong.

(I am sending an MsgPack object together with some type information over websocket, so only the second part of the websocket frame contains the data to deserialize)

MWE:
```
const buf = new ArrayBuffer(10);
const arr0 = new Uint8Array(buf);
const arr1 = new Uint8Array(buf, 1);
for (let i = 0; i < arr0.length; i++) {
	arr0[i] = 255;
}
for (let i = 0; i < arr1.length; i++) {
	arr1[i] = 0;
}
arr1[0] = 0xcb;
```
`arr1` should then deserialize to 0, but it does not. (I have found the cause and will issue a pull request soon)

### PR DESCRIPTION
**Pull request by tisztamo**
Fixes #14

### CODE REVIEW

**Comment by HasithaGunasinghe** [comment]
Any idea on when this fix will be merged to the master branch?

**Comment by ygoe** [comment]
@tisztamo seems to have lost interest. I'm not familiar with the code review tools here and don't see a way to handle this on my side. I could do the work manually, without this PR, though. Or simply accept it as-is and then fix up things separately.

**Comment by tisztamo** [comment]
I am still interested (using my fork in the meantime), but it is not clear what I can do to move forward. I thought you just have to merge the PR to have the fix and the new tests in master. What does "then fix up things separately" mean?

**Comment by ygoe** [comment]
I have submitted a review feedback previously. Have you seen it?

**Comment by tisztamo** [comment]
I got no alert from github and I cannot find anything now. It say "No reviews" on this page. Could you please write it again? (maybe as a comment here)

**Comment by ygoe** [comment]
Probably can't repeat this as it's still pending. This screenshot is from further up the page, not sure why you don't see it. GitHub is strange.

grafik

**Comment by tisztamo** [comment]
It seems to me that the review is not yet submitted, you have to click the submit button. The exact meaning of the three option is not clear to me, but if you leave it on "comment", I hopefully can fix it by accepting your suggested change.

**Comment by ygoe** [comment]
@tisztamo Thanks for the info. I've never used this before, seems a little unintuitive. I could even accept my change myself and then merge the whole thing. Thanks again for the fix! And sorry for the delay.

**Pull request merged**
